### PR TITLE
week-11

### PR DESCRIPTION
**Pull request by f789520**
老師好:
丁仁傑
Guide - Part 3 作業網址如下 

http://3.115.236.143:3000/
http://3.115.236.143:3000/attraction/10

### CODE REVIEW

**Comment by cwpeng** [comment]
Your server is down for now.

**Comment by f789520** [comment]
restart server now~
忘記用nohup 指令 抱歉
在麻煩老師審核

**Comment by cwpeng** [comment]
1. Lack of viewport meta tag.
2. Layout exceeds screen width in small to middle size devices.

未命名-6

**Comment by f789520** [comment]
修正 再麻煩老師審核 謝謝

**Comment by cwpeng** [comment]
1. OK.
2. No fixed.

未命名-2

**Comment by f789520** [comment]
2. fixd~

**Comment by cwpeng** [comment]
1. viewport is break again.
2. no fixed actually.

If you cannot get my point, feel free to message/talk to me for clarification.

**Comment by f789520** [comment]
修正 一些細節 ( 箭頭位置 按鈕透明度) 
不知道行不行
在麻煩老師審核

**Comment by cwpeng** [comment]
Cannot connect to server. Keep server running 24 hours is our duty.

**Comment by f789520** [comment]
Sorry sir.
已重啟

**Comment by cwpeng** [comment]
Space between navigator and image slider is too large in some devices, it should be 40px specified in design. Circles in slider is out of the bottom of slider in some devices.

未命名-2

**Comment by f789520** [comment]
希望有修正到
再麻煩老師審核 謝謝!
image

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
